### ISSUE TITLE
Tool use and other "reasoning gaps"

### ISSUE THREAD

**Issue by abhimanyupallavisudhir** [ArjunPanickssery/math_problems_debate#11]
**Tool use**

([basically reimplement Jackson Kaunismaa's old PR in more generality for the new LLM utils code](https://github.com/ArjunPanickssery/math_problems_debate/pull/6/files))

 - [x] modify `llm_utils` to integrate tool use 
 - [x] modify each debater etc. to enable particular tools in their configuration
 - [x] implement calculator tool for math debate as a starting toy

**Other reasoning gaps**

- [ ] Allow debaters but not judges to use chain-of-thought, tree-of-thought, etc.
- [ ] Set-up where a judge *can* use a tool, but at a much higher cost than the debater -- e.g. looking up a database, etc.

**Comment by JacksonKaunismaa** [comment]
I think the tool-use-new branch handles the first 3 bullets. 

What do you mean about "at a much higher cost than the debater," for the final point? The only way I think judges could use tools is if it's like a CoT judge that can call tools during the thinking phase, which wouldn't be too hard to implement with what we have.
